### ISSUE TITLE
关于统计平均周转时间和带权周转时间

### ISSUE THREAD

**Issue by writingdoge** [Gavin2OO4/CCNUOS-Group-6#2]
![image](https://github.com/user-attachments/assets/e7d68da7-2f9f-482e-ad7c-0996796e47cd)
**貌似还要做这个**
**谁来写一下**

**Comment by Gavin2OO4** [comment]
I have added the code for this section to my branch. If possible, you can help me check it.

**Comment by writingdoge** [comment]
> I have added the code for this section to my branch. If possible, you can help me check it.

Thanks.

**Comment by writingdoge** [comment]
> I have added the code for this section to my branch. If possible, you can help me check it.

Thanks.
